### ISSUE TITLE
Add participants to Rhea import

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/pyobo#167]
Would be useful to have rhea->chebi edges

- #95

"participants" is struck out - was there a reason for this?

**Comment by cthoyt** [comment]
Not sure why I didn't do this, do you have anyone on your team who wants to make a PR?

**Comment by cmungall** [comment]
@balhoff likely won't touch python but he can at least advise us on how to do this

Jim, the code is pretty straightforward here:
https://github.com/pyobo/pyobo/blob/main/src/pyobo/sources/rhea.py

Maybe you could feed us the right SPARQL to use.

w.r.t the modeling, I think we should be as truthful to the source as possible. In particular, I think we should have "left" and "right" relations (potentially adding these to RO even though this will cause consternation). I don't think we should roll up to has-participant as we do in GO. And I don't think we should try a complicated OWL union.

there is an argument for only putting the participants on the child nodes where direction is known, and using has-input and has-output

for stoi, I don't think we should have a complicated nested structure. I think putting stoi on as axiom annotations should be fine.

**Comment by balhoff** [comment]
Here's some SPARQL we use to create a somewhat simplified graph including the reaction participants: https://github.com/geneontology/go-ontology/blob/master/src/sparql/construct-rhea-reactions.sparql
