### ISSUE TITLE
Python 3.12 compatibility

### ISSUE THREAD

**Issue by kkaris** [biopragmatics/pyobo#190]
The builtin `pkg_resource` is no longer available in 3.12, see the 'Attention' box at the beginning of https://setuptools.pypa.io/en/latest/pkg_resources.html

This affects a couple of lines in the code: https://github.com/biopragmatics/pyobo/blob/main/src/pyobo/xrefdb/sources/__init__.py#L10

I have not had the time to check if this is the only blocker for 3.12 compatibility, but this is one of them at least.

**Comment by cthoyt** [comment]
Closed by #193
